# Generated by Django 3.0.2 on 2020-03-08 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0002_auto_20200306_0027'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='description',
            field=models.CharField(default='default_description', max_length=200),
            preserve_default=False,
        ),
    ]
